lib: [
  "_build/install/default/lib/bx_plugin/META"
  "_build/install/default/lib/bx_plugin/bx_plugin.a"
  "_build/install/default/lib/bx_plugin/bx_plugin.cma"
  "_build/install/default/lib/bx_plugin/bx_plugin.cmi"
  "_build/install/default/lib/bx_plugin/bx_plugin.cmt"
  "_build/install/default/lib/bx_plugin/bx_plugin.cmx"
  "_build/install/default/lib/bx_plugin/bx_plugin.cmxa"
  "_build/install/default/lib/bx_plugin/bx_plugin.ml"
  "_build/install/default/lib/bx_plugin/dune-package"
  "_build/install/default/lib/bx_plugin/opam"
]
lib_root: [
  "_build/install/default/lib/coq/user-contrib/bx_plugin/Coq/sample.glob" {"coq/user-contrib/bx_plugin/Coq/sample.glob"}
  "_build/install/default/lib/coq/user-contrib/bx_plugin/Coq/sample.v" {"coq/user-contrib/bx_plugin/Coq/sample.v"}
  "_build/install/default/lib/coq/user-contrib/bx_plugin/Coq/sample.vo" {"coq/user-contrib/bx_plugin/Coq/sample.vo"}
  "_build/install/default/lib/coq/user-contrib/bx_plugin/bx_plugin.glob" {"coq/user-contrib/bx_plugin/bx_plugin.glob"}
  "_build/install/default/lib/coq/user-contrib/bx_plugin/bx_plugin.v" {"coq/user-contrib/bx_plugin/bx_plugin.v"}
  "_build/install/default/lib/coq/user-contrib/bx_plugin/bx_plugin.vo" {"coq/user-contrib/bx_plugin/bx_plugin.vo"}
]
libexec: [
  "_build/install/default/lib/bx_plugin/bx_plugin.cmxs"
]
